### ISSUE TITLE
Value of type 'FlapViewBuilder' has no member 'backgroundColor'

### ISSUE THREAD

**Issue by jorgecasariego** [yannickl/Splitflap#1]
I'm using Pods to do the same example that is in the repository but I have this error and I don't know to resolve.

thanks

![captura de pantalla 2015-11-17 a las 6 01 35 p m](https://cloud.githubusercontent.com/assets/2581647/11224744/4bf694be-8d55-11e5-8f33-f187871749c8.png)

![captura de pantalla 2015-11-17 a las 6 01 25 p m](https://cloud.githubusercontent.com/assets/2581647/11224761/6294dd84-8d55-11e5-8090-689b3708e49c.png)

**Comment by yannickl** [comment]
Sorry it's my bad, the access controls was _internal_ instead of 'public'. I just push a new version of the pod, it should works now.

**Comment by jorgecasariego** [comment]
Yea! Now is working! Thanks @yannickl 

I've added your repo to my list of resources that you can see here: https://github.com/jorgecasariego/awesome-swift/

**Comment by yannickl** [comment]
That's great, thank you!
