### ISSUE TITLE
Swift Package Manager not resolving library

### ISSUE THREAD

**Issue by theoriginalbit** [yannickl/Splitflap#15]
I'm attempting to add this package to my project via the `Add Package Dependency` feature in Xcode 11 and I get the following error:

```
The package dependency graph can not be resolved; unable find any available tag for the following requirements:
https://github.com/yannickl/Splitflap.git — 4.1.0..<5.0.0
```

I believe this is because you've missed out the `products` and `targets` section in the `Package.swift` file. A simple example can be found in [JGProgressHUD's `Packages.swift`](https://github.com/JonasGessner/JGProgressHUD/blob/master/Package.swift)

**Comment by phongleq** [comment]
I submitted a pull request that fixes this issue. You can point to my fork for the time being. 

https://github.com/yannickl/Splitflap/pull/16

**Comment by yannickl** [comment]
@theoriginalbit thank you for reporting it and sorry for the late, I have been really busy for few months now. Thanks to @phongleq it should be ok now. :)

**Comment by theoriginalbit** [comment]
awesome, thanks guys 🙂
