### ISSUE TITLE
Two problem :

### ISSUE THREAD

**Issue by ZsIsMe** [yannickl/Splitflap#2]
Two problem :
1.I could not compile because in SplitflapTokens.swift :

 Cannot invoke 'map' with an argument list of type '((CVarArgType) -> String)'

 I use Xcode 7.0.1 , is that the reason I occur the problem?
![2015-12-10 11 47 52](https://cloud.githubusercontent.com/assets/7468754/11706462/f9108bf6-9f33-11e5-8603-0c75ac056c62.png)
1. after I delete the 'wrong' code, I run the demo ,but the animation is strange ：
   sometime the low part was dismiss, why? 

![2015-12-10 11 26 51](https://cloud.githubusercontent.com/assets/7468754/11706440/cd092b58-9f33-11e5-933b-33aa429a5ea1.png)

Thanks!

**Comment by yannickl** [comment]
Hi,
1. It works perfectly with Xcode 7.1 and over, I can't test on my computer so I don't really know. Following  this link http://stackoverflow.com/questions/29953390/swift-compiler-error-cannot-invoke-map-with-an-argument-list-of-type you should add `Int -> String in` inside the `map` block and see whether it works.
2. May be it is a bug. Sometimes when I update the texts too fast it can appears. I'll investigate on this.

Thank you
