### ISSUE TITLE
TwelveHourClock format

### ISSUE THREAD

**Issue by deivuh** [yannickl/Splitflap#5]
Hi!

First of all thanks for this great component. This is exactly was I was looking for and I like that it has Swift 3 support already. 

I was looking at the pre defined tokens in SplitflapTokens. I think the TwelveHourClock token should have a 2 digits format just like the 24hour and minutes/seconds one.

**Comment by yannickl** [comment]
It works as expected. Except that each flap display one digit, like in this photo:

![splitflap1](https://cloud.githubusercontent.com/assets/798235/18808090/e38ee2e2-8258-11e6-8cc6-bc729b527f66.jpg)

Of course you can create clocks with 2 digits per flap but the 1 digit per flap covers more use cases.

**Comment by deivuh** [comment]
I see, it was intended then. I will close the PR.

**Comment by Danielthenew** [comment]
Hey 
I also wanna use it to print a clock i have set SplitflapTokens.TwelveHourClock but i can´t set the numbers when i try it with splitflap.setText("11:59", animated: true) in a button it print me hours but he print not the double point and the minutes.   

numberOfFlapsInSplitflap i have set to 5 

Thanks for your answer :)

**Comment by yannickl** [comment]
@Danielthenew This is because the `:` is not available in the `TwelveHourClock` token list.

You should add it in the `tokensInSplitflap` method:

``` swift
func tokensInSplitflap(_ splitflap: Splitflap) -> [String] {
  return SplitflapTokens.TwelveHourClock + ":"
}
```
